server:
  port: 443
  ssl:
    key-store: 3958466_haodu123.cn.pfx
    key-store-password: l4AmSKMq
    key-store-type: PKCS12
    enabled: true
#jdbc
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stockinfo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 60000
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  typeAliasesPackage: com.stockinfo.entity
  mapperLocations: classpath:mapper/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




