server:
  port: 443
  ssl:
    key-store: classpath:3831019_31094ld435.wicp.vip.pfx
    key-store-password: yr4vt6eJ
    key-store-type: PKCS12
#jdbc
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stockinfo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 60000
mybatis:
  typeAliasesPackage: com.stockinfo.entity
  mapperLocations: classpath:mapper/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql




